# Generated by Django 5.0.6 on 2024-05-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="color_product_variants",
                to="management.productcolor",
                verbose_name="color",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="total_stock_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=20,
                null=True,
                verbose_name="total price",
            ),
        ),
    ]
