# Generated by Django 5.0.6 on 2024-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_alter_productvariant_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinvoice",
            name="cash_on_delivery",
            field=models.BooleanField(default=False, verbose_name="cash on delivery"),
        ),
    ]
