# Generated by Django 5.0.6 on 2024-05-30 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_remove_productinvoice_cash_on_delivery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
