# Generated by Django 5.0.6 on 2024-06-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_remove_product_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counter",
                    models.PositiveIntegerField(default=0, verbose_name="counter"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="productinvoice",
            name="product_variant",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="transaction_successful",
            field=models.BooleanField(
                default=False, verbose_name="transaction successful"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="quantity"),
        ),
        migrations.AddField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_sp_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=20,
                null=True,
                verbose_name="total selling price",
            ),
        ),
        migrations.AddField(
            model_name="productinvoice",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_invoices",
                to="management.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="productinvoice",
            name="size",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="size_product_invoices",
                to="management.productsize",
                verbose_name="size",
            ),
        ),
        migrations.AlterField(
            model_name="productinvoice",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="quantity"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="counter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="management.invoicecounter",
                verbose_name="counter",
            ),
        ),
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_transactions",
                        to="management.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_transactions",
                        to="management.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="size_transactions",
                        to="management.productsize",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
