# Generated by Django 5.0.6 on 2024-05-25 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(?:(?:\\+|00)88|01)?\\d{11}$"
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
