# Generated by Django 5.0.6 on 2024-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=32, verbose_name="name"),
        ),
    ]
